apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: user-service
          image: "user-service:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: SQLITE_DB_PATH
              value: /app/sqlite.db
